schema = 3

[mod]
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/fatih/color"]
    version = "v1.16.0"
    hash = "sha256-Aq/SM28aPJVzvapllQ64R/DM4aZ5CHPewcm/AUJPyJQ="
  [mod."github.com/google/go-configfs-tsm"]
    version = "v0.3.3-0.20240919001351-b4b5b84fdcbc"
    hash = "sha256-Gz7xKpSZNQelOVQgaZ/Ld83iBcdvcaT7Os56434/JCg="
  [mod."github.com/google/go-sev-guest"]
    version = "v0.12.1"
    hash = "sha256-hqa1ms7V4eBbSoH4oUChsp+QoWMUItbaWhbL+rgWG7c="
  [mod."github.com/google/go-tdx-guest"]
    version = "v0.3.2-0.20241009005452-097ee70d0843"
    hash = "sha256-ZvqoLlg4VfnGOGGF2PN65qpdmiVFqfPpu5iLjkQe2ao="
  [mod."github.com/google/go-tpm"]
    version = "v0.9.7"
    hash = "sha256-JxETYLaetCufzJp/srXqwFZGDuYSl0jBM5So0+ovYZ4="
  [mod."github.com/google/go-tpm-tools"]
    version = "v0.4.5"
    hash = "sha256-FfTK+TnvuzUqelkLp3b9H1tYF1DVU64QFhMY4iz3yOU="
  [mod."github.com/google/logger"]
    version = "v1.1.1"
    hash = "sha256-92ECLiBcM8ahLducThWxaAzB0P3wA72Wycu66fetTfQ="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/ncruces/go-sqlite3"]
    version = "v0.30.3"
    hash = "sha256-Yflzb/7EDz60mcWZedInaxT8T9v/GKZBiIOGFkkj6y0="
  [mod."github.com/ncruces/julianday"]
    version = "v1.0.0"
    hash = "sha256-EelxOI6DLHy0jYnAcTeda24wLWkGOYuFtoJvuDg874s="
  [mod."github.com/neilotoole/jsoncolor"]
    version = "v0.7.1"
    hash = "sha256-Vl0J4GbQXFaUHNhYLUjeEnjbAE5TowQpFVm1HXBtf0E="
  [mod."github.com/niemeyer/muslnet"]
    version = "v0.0.0-20250923220305-4b81d3c72602"
    hash = "sha256-foqqh2zlLNW6Dq4pnocX4Xdn/+edCAKfhaNao091uE4="
  [mod."github.com/nwidger/jsoncolor"]
    version = "v0.3.2"
    hash = "sha256-ibwPUPCLaBHKRYo93eaPlqlRFB2MW8f/XlImBkg2q2c="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/segmentio/asm"]
    version = "v1.1.3"
    hash = "sha256-T26b7yreVbvHVaUSLRnSeF+p4fmVhyTNIj7HzL83deA="
  [mod."github.com/segmentio/encoding"]
    version = "v0.3.6"
    hash = "sha256-XrxOwMPaY3tRdZkQr9Njw5hI1HeheGU3uI4DbH8bb7w="
  [mod."github.com/stretchr/testify"]
    version = "v1.9.0"
    hash = "sha256-uUp/On+1nK+lARkTVtb5RxlW15zxtw2kaAFuIASA+J0="
  [mod."github.com/syumai/workers"]
    version = "v0.27.0"
    hash = "sha256-acWyf6OhF+2vpejyVsTXF250RlsY52gWvLz/2SvYueU="
  [mod."github.com/tetratelabs/wazero"]
    version = "v1.10.1"
    hash = "sha256-b0uZWDO0++af38zJ0TS9FGLM/Ver5dfkBiqas3tg388="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."golang.org/x/crypto"]
    version = "v0.45.0"
    hash = "sha256-IpNesJYxFcs2jGvagwJrUD/gsJfA3UiETjQwYByXxSY="
  [mod."golang.org/x/sys"]
    version = "v0.38.0"
    hash = "sha256-1+i5EaG3JwH3KMtefzJLG5R6jbOeJM4GK3/LHBVnSy0="
  [mod."golang.org/x/term"]
    version = "v0.37.0"
    hash = "sha256-w7OZlNTd5sAhnDxrl9lKpKc1U/s2+MyZnmQPllJopMQ="
  [mod."golang.org/x/text"]
    version = "v0.31.0"
    hash = "sha256-AT46RrSmV6+/d5FDhs9fPwYzmQ7WSo+YL9tPfhREwLw="
  [mod."google.golang.org/protobuf"]
    version = "v1.35.1"
    hash = "sha256-4NtUQoBvlPGFGjo7c+E1EBS/sb8oy50MGy45KGWPpWo="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."hermannm.dev/devlog"]
    version = "v0.6.0"
    hash = "sha256-vWecKv3H3LOqjbJFxb10M9V5jB4KHwdtT/6X8gdmIBw="
  [mod."tinygo.org/x/drivers"]
    version = "v0.33.0"
    hash = "sha256-N8Gfg78dlYVfdDqEpEs8ujtQrTsew199fUx19hXYcMQ="
