schema = 3

[mod]
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/fatih/color"]
    version = "v1.16.0"
    hash = "sha256-Aq/SM28aPJVzvapllQ64R/DM4aZ5CHPewcm/AUJPyJQ="
  [mod."github.com/google/go-configfs-tsm"]
    version = "v0.3.3-0.20240919001351-b4b5b84fdcbc"
    hash = "sha256-Gz7xKpSZNQelOVQgaZ/Ld83iBcdvcaT7Os56434/JCg="
  [mod."github.com/google/go-sev-guest"]
    version = "v0.14.0"
    hash = "sha256-7OtU0mbvC88aRh9oSS01e6KgU/+QNGYYkSxeaWcRynA="
  [mod."github.com/google/go-tdx-guest"]
    version = "v0.3.2-0.20241009005452-097ee70d0843"
    hash = "sha256-ZvqoLlg4VfnGOGGF2PN65qpdmiVFqfPpu5iLjkQe2ao="
  [mod."github.com/google/go-tpm"]
    version = "v0.9.7"
    hash = "sha256-JxETYLaetCufzJp/srXqwFZGDuYSl0jBM5So0+ovYZ4="
  [mod."github.com/google/go-tpm-tools"]
    version = "v0.4.7"
    hash = "sha256-Wwecp81g7cJHQNslkibj7V2RstFxL0Yw9s9vCgHanQI="
  [mod."github.com/google/logger"]
    version = "v1.1.1"
    hash = "sha256-92ECLiBcM8ahLducThWxaAzB0P3wA72Wycu66fetTfQ="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/ncruces/go-sqlite3"]
    version = "v0.30.4"
    hash = "sha256-9dyO5ih8x4ReYtsM5cF4JKeq2bu+9ZAY1WcUDAhow/A="
  [mod."github.com/ncruces/julianday"]
    version = "v1.0.0"
    hash = "sha256-EelxOI6DLHy0jYnAcTeda24wLWkGOYuFtoJvuDg874s="
  [mod."github.com/neilotoole/jsoncolor"]
    version = "v0.7.1"
    hash = "sha256-Vl0J4GbQXFaUHNhYLUjeEnjbAE5TowQpFVm1HXBtf0E="
  [mod."github.com/niemeyer/muslnet"]
    version = "v0.0.0-20250923220305-4b81d3c72602"
    hash = "sha256-foqqh2zlLNW6Dq4pnocX4Xdn/+edCAKfhaNao091uE4="
  [mod."github.com/nwidger/jsoncolor"]
    version = "v0.3.2"
    hash = "sha256-ibwPUPCLaBHKRYo93eaPlqlRFB2MW8f/XlImBkg2q2c="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/segmentio/asm"]
    version = "v1.1.3"
    hash = "sha256-T26b7yreVbvHVaUSLRnSeF+p4fmVhyTNIj7HzL83deA="
  [mod."github.com/segmentio/encoding"]
    version = "v0.3.6"
    hash = "sha256-XrxOwMPaY3tRdZkQr9Njw5hI1HeheGU3uI4DbH8bb7w="
  [mod."github.com/stretchr/testify"]
    version = "v1.9.0"
    hash = "sha256-uUp/On+1nK+lARkTVtb5RxlW15zxtw2kaAFuIASA+J0="
  [mod."github.com/syumai/workers"]
    version = "v0.27.0"
    hash = "sha256-acWyf6OhF+2vpejyVsTXF250RlsY52gWvLz/2SvYueU="
  [mod."github.com/tetratelabs/wazero"]
    version = "v1.11.0"
    hash = "sha256-bXmvMmQLsfyEa3C1kjE0AAVhGzj2tIiO67MxI3otMo8="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."golang.org/x/crypto"]
    version = "v0.46.0"
    hash = "sha256-I8N/spcw3/h0DFA+V1WK38HctckWIB9ep93DEVCALxU="
  [mod."golang.org/x/sys"]
    version = "v0.39.0"
    hash = "sha256-dxTBu/JAWUkPbjFIXXRFdhQWyn+YyEpIC+tWqGo0Y6U="
  [mod."golang.org/x/term"]
    version = "v0.38.0"
    hash = "sha256-46mX91XGJqii6SUESiU5mLVJDBOfKYCp+408m91hrMw="
  [mod."golang.org/x/text"]
    version = "v0.32.0"
    hash = "sha256-9PXtWBKKY9rG4AgjSP4N+I1DhepXhy8SF/vWSIDIoWs="
  [mod."google.golang.org/protobuf"]
    version = "v1.35.1"
    hash = "sha256-4NtUQoBvlPGFGjo7c+E1EBS/sb8oy50MGy45KGWPpWo="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."hermannm.dev/devlog"]
    version = "v0.6.0"
    hash = "sha256-vWecKv3H3LOqjbJFxb10M9V5jB4KHwdtT/6X8gdmIBw="
  [mod."tinygo.org/x/drivers"]
    version = "v0.34.0"
    hash = "sha256-UQQN5z4JvCIjSh/IPkh7upM+TP9HBj+2X0YP1bTP1qk="
